json_post_text = {'main_title': "OpenAI's Path to Human-Level AI", 'subtitle': 'Exploring the 5 Levels to Achieve AGI',
                  'post_caption': "🤖 OpenAI is on a mission to reach human-level intelligence with its AI systems, and it's closer than you might think! The company has outlined a five-level system to track its progress toward Artificial General Intelligence (AGI). Currently, OpenAI is at the first level, which focuses on conversational AI, but it's already making strides toward level two. 🌐\n\n🧠 The second level, known as 'Reasoners,' involves AI that can perform basic problem-solving tasks, akin to a human with a doctorate but without access to tools. Imagine an AI that can think critically and solve complex problems! The third level, 'Agents,' will see AI performing various actions for several days on behalf of its user. 🚀\n\n💡 The fourth level, 'Innovators,' is where things get really exciting. At this stage, AI will be capable of developing new inventions, pushing the boundaries of innovation. OpenAI's research with GPT-4 has already shown human-like reasoning skills, indicating that we're on the right path. Stay tuned as we follow this incredible journey! ",
                  'hashtags': '#ArtificialGeneralIntelligence #OpenAIProgress #AIInnovation #FutureOfAI #AILevels #ConversationalAI #Reasoners #AIResearch #TechNews #AIAdvancements #HumanLevelAI #InnovativeAI #AIJourney #NextGenAI #AIUpdates'}




image_prompt = "Visualize the future of biological research with Evo: A sleek, high-tech laboratory illuminated by soft, blue lights, showcasing a large, transparent holographic display of a DNA helix in the center. Around the room, scientists in futuristic attire are engaged in various activities, from analyzing genetic data on floating screens to conducting experiments with advanced robotic equipment. The atmosphere is one of focused innovation, with the Arc Institute and Stanford logos subtly integrated into the background, symbolizing the collaboration behind Evo's development. Highlight the essence of groundbreaking AI technology merging with the intricate beauty of genetic sequences, embodying the dawn of a new era in genomics."
img_path = 'images/generated/2024-03-17-11-58.png'
edited_img_path = 'images/posts/2024-03-05-12-11.png'
